Lab07 - Inter-Integrated Circuit
UPB-FILS-MA/upb-fils-ma.github.io pull request #101
Opened 2024-04-15 18:50 UTC by TeodoraMiu

### Pull Request Overview

This pull request adds lab07 - I2C.

### Testing Strategy

This pull request was tested by running the examples locally.

### TODO or Help Wanted

This pull request still needs review.

### Build

- [x] Ran `npm build`.

### Author

Signed-off-by: Teodora Miu <teodora.miu@stud.fils.upb.ro>

2024-04-15 19:04 UTC, alexandruradovici requested changes

2024-04-15 19:04 UTC, alexandruradovici commented on docs/lab/07/index.md
> +4. Show the temperature and pressure values on the screen. (**2p**)
Can we add another exercise with USB? The purpose being to register a serial device? We can start from an embassy example that echoes the text and ask the students to change the name of the device and echo back the reversed text.

2024-04-16 04:23 UTC, DTeodor-Alexaandru requested changes

2024-04-16 04:23 UTC, DTeodor-Alexaandru commented on docs/lab/07/index.md
> +This is called *open-drain connection*. You can read more about how it works [here](https://www.ti.com/lit/an/sbaa565/sbaa565.pdf?ts=1712891793335#:~:text=I2C%20is%20a%20two%2Dwire,and%20receive%20co
Open drain uses only pull up resistor and connects directly to the ground for logic LOW. Pull down resistors are used for push-pull configuration(ex: spi) and is recommanded only if there is another CS pin

2024-04-16 12:21 UTC, DTeodor-Alexaandru approved these changes

2024-04-16 13:01 UTC, alexandruradovici requested changes

2024-04-16 16:23 UTC, TeodoraMiu commented on docs/lab/07/images/i2c_7bit_address_transmission.svg
I don't see any difference between the image I used and the one in the slides. There is an ack after every byte sent.

2024-04-16 18:08 UTC, DTeodor-Alexaandru approved these changes

2024-04-16 18:22 UTC, alexandruradovici requested changes

2024-04-16 18:22 UTC, alexandruradovici commented on docs/lab/07/images/i2c_7bit_address_transmission.svg
There is an updated image in the slides, this one has an error, ack is read when CLK is high.

2024-04-16 18:57 UTC, alexandruradovici approved these changes

2024-04-16 18:57 UTC, DTeodor-Alexaandru approved these changes

2024-04-16 19:02 UTC, merged