Project_documentation_Kalman Temperature Alert System
UPB-FILS-MA/upb-fils-ma.github.io pull request #131
Opened 2024-05-02 11:40 UTC by Fote20003

### Pull Request Overview

This pull request adds/changes/fixes...

### Testing Strategy

This pull request was tested by...

### TODO or Help Wanted

This pull request still needs...

### Build

- [ ] Ran `npm build`.

### Author

Signed-off-by: Your Name <Your Email@example.com>

2024-05-02 22:05 UTC, irina-b-dev reviewed
Please put the index.md in a folder named : maria-irina.fotescu_teo-antonio.economu

2024-05-02 22:06 UTC, irina-b-dev reviewed
Make a single branch and pull request for both authors.

2024-05-03 09:48 UTC, alexandruradovici requested changes

2024-05-03 09:48 UTC, alexandruradovici commented on docs/project/2024/Project_documentation/index.md
> +
Please add a one line description of the project here.

2024-05-03 09:48 UTC, alexandruradovici commented on docs/project/2024/Project_documentation/index.md
Please rename the folder to your curs.uob.ro username.

2024-05-03 09:48 UTC, alexandruradovici commented on docs/project/2024/Project_documentation/index.md
> +| ------------------------------------------------------------------------------------------------------- | ------------------- | ---------------------------------------------------------------------
```suggestion
|-|-|-|
```

2024-05-05 20:03 UTC, closed without merging

2024-05-05 20:03 UTC, alexandruradovici commented
Closing as duplicate of #242.