Chiorean Rebeca project documentation
UPB-FILS-MA/upb-fils-ma.github.io pull request #134
Opened 2024-05-02 14:52 UTC by ChioreanRebeca

### Pull Request Overview

This pull request adds/changes/fixes...

### Testing Strategy

This pull request was tested by...

### TODO or Help Wanted

This pull request still needs...

### Build

- [ ] Ran `npm build`.

### Author

Signed-off-by: Your Name <Your Email@example.com>

2024-05-02 15:27 UTC, alexandruradovici approved these changes

2024-05-02 17:01 UTC, ChioreanRebeca commented
i hope this solved the issue :)

2024-05-02 20:40 UTC, alexandruradovici approved these changes

2024-05-02 20:41 UTC, alexandruradovici requested changes

2024-05-02 20:41 UTC, alexandruradovici commented on docs/project/2024/Rebeca_CHIOREAN/architectureChioreanLita.png
Rename the folder using your username.

2024-05-03 04:36 UTC, ChioreanRebeca commented on docs/project/2024/Rebeca_CHIOREAN/architectureChioreanLita.png
I used my curs.upb username as mentioned on Teams " your_curs.upb.ro_username ". Should I change the folder name to my GitHub username?

2024-05-03 07:02 UTC, alexandruradovici commented on docs/project/2024/Rebeca_CHIOREAN/architectureChioreanLita.png
Is your username *Rebecca_CHIOREAN*, spelled like this?

2024-05-03 08:01 UTC, ChioreanRebeca commented on docs/project/2024/Rebeca_CHIOREAN/architectureChioreanLita.png
No, my username is Rebeca CHIOREAN (with just one "c").

2024-05-03 08:22 UTC, alexandruradovici commented on docs/project/2024/Rebeca_CHIOREAN/architectureChioreanLita.png
Rhe username cannot be with spaces, it is the part before the @ of your email.

2024-05-03 08:43 UTC, ChioreanRebeca commented on docs/project/2024/Rebeca_CHIOREAN/architectureChioreanLita.png
Ok I undestarnd now. Username is rebeca.chiorean with small letters.

2024-05-03 09:01 UTC, ChioreanRebeca commented on docs/project/2024/Rebeca_CHIOREAN/architectureChioreanLita.png
I hope it is okay now.

2024-05-03 09:45 UTC, alexandruradovici requested changes

2024-05-03 09:45 UTC, alexandruradovici commented on docs/project/2024/rebeca.chiorean/index.md
> +:::info
One more thing, please add a one line description koi the project here.

2024-05-03 10:02 UTC, alexandruradovici approved these changes

2024-05-03 10:14 UTC, irina-b-dev approved these changes

2024-05-03 10:19 UTC, merged