Project documentation for Pet Feeder
UPB-FILS-MA/upb-fils-ma.github.io pull request #152
Opened 2024-05-02 21:25 UTC by EdwardAdelin

### Pull Request Overview

This pull request adds/fixes Documentation and Diagram.

Signed-off-by: Finichiu Eduard Adelin

2024-05-02 21:33 UTC, alexandruradovici requested changes

2024-05-02 21:33 UTC, alexandruradovici commented on docs/project/2024/eduard.finichiu/index.md
> +# Project Name
Please name your project.

2024-05-02 21:33 UTC, alexandruradovici commented on docs/project/2024/eduard.finichiu/index.md
> +| -------------------------------------------------------------------------------------------------------------------- | ---------------------- | -----------------------------------------------------
```suggestion
|-|-|-|
```

2024-05-02 21:33 UTC, alexandruradovici commented on docs/project/2024/eduard.finichiu/index.md
> +| ---------------------------------------------------------- | ------------------------------------------------- | -------------------------------------- | ------------------------------------ |
```suggestion
|-|-|-|-|
```

2024-05-02 21:33 UTC, alexandruradovici commented on docs/project/2024/eduard.finichiu/index.md
> +| [tokio](https://docs.rs/tokio/latest/tokio/)               | runtime for writing reliable network applications | Used for speed of network applications |
I don't think you can use tokio with embedded systems.

2024-05-02 21:33 UTC, alexandruradovici commented on docs/project/2024/eduard.finichiu/index.md
> +| [pico sdk rust](https://docs.rs/pico-sdk/latest/pico_sdk/) | rust binding and wrappers                         | pico sdk for rust                      |
This library is not for the Raspberry Pi Pico.

2024-05-02 21:33 UTC, alexandruradovici commented on docs/project/2024/eduard.finichiu/index.md
> +3. [link](https://mi-home.ro/products/xiaomi-smart-pet-food-feeder)
Please use a title for your links, that title is displayed to the user.

2024-05-03 04:23 UTC, TeodoraMiu submitted a review, later dismissed

2024-05-03 06:50 UTC, alexandruradovici commented on docs/project/2024/eduard.finichiu/index.md
> +| ---------------------------------------------------------- | ------------------------------------------------- | -------------------------------------- | ------------------------------------ |
Is this resolved?

2024-05-03 06:50 UTC, alexandruradovici commented on docs/project/2024/eduard.finichiu/index.md
> +| -------------------------------------------------------------------------------------------------------------------- | ---------------------- | -----------------------------------------------------
Is this resolved?

2024-05-03 06:50 UTC, alexandruradovici requested changes

2024-05-03 06:50 UTC, alexandruradovici commented on docs/project/2024/eduard.finichiu/index.md
> +| ---------------------------------------------------------------- | ---------------------- | ---------------------------------------------------------------------------------------------------------
```suggestion
|-|-|-|
```

2024-05-03 10:31 UTC, alexandruradovici requested changes

2024-05-03 10:31 UTC, alexandruradovici commented on docs/project/2024/eduard.finichiu/index.md
> +Pet Feeder
```suggestion
# Pet Feeder

```

Add a one line description of your project under the title.

2024-05-03 11:59 UTC, alexandruradovici requested changes

2024-05-03 11:59 UTC, alexandruradovici commented on docs/project/2024/eduard.finichiu/index.md
> +| -------------------------------------------------------------------------------------------------------------------- | ---------------------- | -----------------------------------------------------
Not resolved

2024-05-03 12:03 UTC, alexandruradovici requested changes

2024-05-03 12:03 UTC, alexandruradovici commented on docs/project/2024/eduard.finichiu/index.md
> +|
```suggestion
|-|-|-|
```

2024-05-03 12:04 UTC, alexandruradovici commented
Please use `npm start` to verify if it looks correct.

2024-05-03 12:57 UTC, alexandruradovici requested changes
Please add your email address to the pull request template.

2024-05-03 13:05 UTC, EdwardAdelin commented
> Please add your email address to the pull request template.

I have added it now. Thank you!

2024-05-03 13:10 UTC, alexandruradovici approved these changes

2024-05-03 17:29 UTC, TeodoraMiu approved these changes

2024-05-03 20:17 UTC, alexandruradovici approved these changes

2024-05-03 20:22 UTC, merged