Project_documentation_WIFIcar
UPB-FILS-MA/upb-fils-ma.github.io pull request #153
Opened 2024-05-02 22:00 UTC by Teodora1807

### Pull Request Overview

### Author

Signed-off-by: Teodora Dumitru <teodumitru18@gmail.com>

2024-05-02 22:17 UTC, irina-b-dev reviewed
Please rename "project_documentation" folder to your username (teodora.dumitru)

2024-05-02 22:21 UTC, irina-b-dev commented on docs/project/2024/project_documentation/index.md
> +| [embedded-graphics](https://github.com/embedded-graphics/embedded-graphics) | 2D graphics library | Used for drawing to the display |
You will probably not need these libraries if you are not using ST7789 display

2024-05-02 22:21 UTC, irina-b-dev commented on docs/project/2024/project_documentation/index.md
> +
Please also add a [block diagram](https://www.eleccircuit.com/understanding-electronics-block-diagrams-with-example/) for your project.

2024-05-04 10:40 UTC, alexandruradovici requested changes

2024-05-04 10:40 UTC, alexandruradovici commented on docs/project/2024/Teodora_Dumitru/index.md
> +
Add a one line description of your project.

2024-05-04 10:40 UTC, alexandruradovici commented on docs/project/2024/Teodora_Dumitru/index.md
> + - how they connect with each other
```suggestion
```

2024-05-04 10:40 UTC, alexandruradovici commented on docs/project/2024/Teodora_Dumitru/index.md
> +| [2 wheels,1 small wheel, 2 motors, platform ] | The kit | [15 RON](second-hand) |
```suggestion
| [2 wheels,1 small wheel, 2 motors, platform ](link here) | The kit | [15 RON](link here) |
```
 If there is no link, delete the square brackets.

2024-05-04 19:09 UTC, alexandruradovici requested changes

2024-05-04 19:09 UTC, alexandruradovici commented on docs/project/2024/Teodora_Dumitru/index.md
> +I intend to do a robot car that can be controlled through a website accessed from the mobile phone or a computer . The website will have on the home page a controller with all 4 directions of movemen
```suggestion
A robot car that can be controlled through a website accessed from the mobile phone or a computer .
```

2024-05-04 19:09 UTC, alexandruradovici commented on docs/project/2024/project_documentation/index.md
Delete this file

2024-05-04 19:09 UTC, alexandruradovici commented on docs/project/2024/Teodora_Dumitru/SS-AM.png
rename the folder to you curs.upb.ro username, that is the part in front of you @stud email.

2024-05-05 11:01 UTC, alexandruradovici requested changes
Please delete all the files and folders that you do not need.

2024-05-05 15:35 UTC, alexandruradovici commented
Please fix the build issue, you have a broken link.

2024-05-05 15:36 UTC, alexandruradovici requested changes

2024-05-05 15:36 UTC, alexandruradovici commented on docs/project/2024/project_documentation/index.md
> +| [Jumper wires]| To ensure the connections between components | [already have]|
```suggestion
| Jumper wires| To ensure the connections between components | already have| 
```

2024-05-05 15:36 UTC, alexandruradovici commented on docs/project/2024/project_documentation/index.md
> +| [2 wheels,1 small wheel, 2 motors, platform ] | The kit | [15 RON](second-hand) |
```suggestion
| [2 wheels,1 small wheel, 2 motors, platform ] | The kit | [15 RON](second-hand) |
```

The *second-hand* generates the build the error.

2024-05-05 16:52 UTC, alexandruradovici requested changes

2024-05-05 16:52 UTC, alexandruradovici commented on docs/project/2024/project_documentation/index.md
This is not solved.

2024-05-05 16:52 UTC, alexandruradovici commented on docs/project/2024/project_documentation/index.md
Please delete this folder.

2024-05-05 20:04 UTC, alexandruradovici commented
@Teodora1807 is this still in progress?

2024-05-05 20:06 UTC, Teodora1807 commented
I have uploaded it

On Sun, 5 May 2024 at 23:04, Alexandru Radovici ***@***.***>
wrote:

> @Teodora1807 <https://github.com/Teodora1807> is this still in progress?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/UPB-FILS-MA/upb-fils-ma.github.io/pull/153#issuecomment-2094931666>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BG6Y7L3NAMYLPDUKCU4ZZ73ZA2GFZAVCNFSM6AAAAABHEQDMEWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAOJUHEZTCNRWGY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-05-05 20:08 UTC, alexandruradovici commented
Is there another pull request? This one needs changes.

2024-05-05 20:14 UTC, alexandruradovici commented
Please delete the unused folder, keep only the folder with your username.

2024-05-05 20:25 UTC, alexandruradovici commented on docs/project/2024/teodora.dumitru1807/index.md
> +
```suggestion
:::info

**Author**: Dumitru Teodora-Iulia \
**GitHub Project Link**: [link_to_github](https://github.com/UPB-FILS-MA/project-Teodora1807.git)

:::
```

2024-05-05 20:28 UTC, alexandruradovici requested changes

2024-05-05 20:28 UTC, alexandruradovici commented on docs/project/2024/teodora.dumitru1807/index.md
> +**GitHub Project Link**: [link_to_github](https://github.com/UPB-FILS-MA/project-Teodora1807.git)
```suggestion
**GitHub Project Link**: https://github.com/UPB-FILS-MA/project-Teodora1807.git
```

2024-05-05 20:41 UTC, alexandruradovici approved these changes

2024-05-05 20:42 UTC, DTeodor-Alexaandru approved these changes

2024-05-05 20:50 UTC, merged