Add project documentation for Rata_Mircea_Andrei
UPB-FILS-MA/upb-fils-ma.github.io pull request #166
Opened 2024-05-03 12:48 UTC by MirceaAndrei

### Pull Request Overview

This pull request adds/changes/fixes the documentation of the project.

### Testing Strategy

This pull request was tested by Rata Mircea Andrei.

### Build

- [ ] Ran `npm build`.

### Author

Signed-off-by: Rata Mircea Andrei <mircea.radu2003@gmail.com>

2024-05-03 12:55 UTC, alexandruradovici requested changes
Please fill the pull request template.

2024-05-03 12:56 UTC, alexandruradovici requested changes

2024-05-03 12:56 UTC, alexandruradovici commented on docs/project/2024/Mircea_Andrei_RAŢĂ/index.md
Rename the folder to your username.

2024-05-03 13:23 UTC, MirceaAndrei commented on docs/project/2024/Mircea_Andrei_RAŢĂ/index.md
The folder has my username and I also update the pull request template.

2024-05-03 20:08 UTC, alexandruradovici requested changes

2024-05-03 20:08 UTC, alexandruradovici commented on docs/project/2024/Mircea_Andrei_RAŢĂ/index.md
> +![System Diagram](https://i.imgur.com/VssvqIb.png)
Please add the diagram to your folder.

2024-05-04 00:19 UTC, MirceaAndrei commented on docs/project/2024/Mircea_Andrei_RAŢĂ/index.md
> +![System Diagram](https://i.imgur.com/VssvqIb.png)
I added the diagram on my folder.

2024-05-04 10:41 UTC, alexandruradovici requested changes

2024-05-04 10:41 UTC, alexandruradovici commented on docs/project/2024/Mircea_Andrei_RAŢĂ/arhitecture.png
Please rename the folder to your curs.upb.ro username.

2024-05-04 10:59 UTC, alexandruradovici commented on docs/project/2024/Mircea_Andrei_RAŢĂ/index.md
Your username is the part in front if @stud....

2024-05-04 11:00 UTC, alexandruradovici requested changes

2024-05-04 11:00 UTC, alexandruradovici commented on docs/project/2024/Mircea_Andrei_RAŢĂ/arhitecture.png
Delete this file.

2024-05-04 11:00 UTC, alexandruradovici commented on docs/project/2024/Mircea_Andrei_RAŢĂ/index.md
Delete this file and folder.

2024-05-04 11:18 UTC, MirceaAndrei commented on docs/project/2024/Mircea_Andrei_RAŢĂ/index.md
I have an issue. On my repository i have only the mircea_andrei.rata folder. I dont have the one that i need to delete ,the Mircea_Andrei_RAŢĂ.What should i do?

2024-05-04 11:40 UTC, MirceaAndrei commented on docs/project/2024/Mircea_Andrei_RAŢĂ/index.md
I deleted the file and folder.

2024-05-04 19:07 UTC, alexandruradovici commented on docs/project/2024/mircea_andrei.rata/index.md
> + A smart burglar alarm system , equipped with motion detection, email alerts and keypad for security.
```suggestion
 A smart burglar alarm system, equipped with motion detection, email alerts and keypad for security.
```

2024-05-04 19:07 UTC, alexandruradovici submitted a review, later dismissed

2024-05-04 19:08 UTC, irina-b-dev approved these changes

2024-05-05 11:15 UTC, alexandruradovici approved these changes

2024-05-05 11:34 UTC, DTeodor-Alexaandru approved these changes

2024-05-05 11:39 UTC, merged