First commit
UPB-FILS-MA/upb-fils-ma.github.io pull request #167
Opened 2024-05-03 13:04 UTC by Raluca3012

### Pull Request Overview

This pull request adds/changes/fixes...

### Testing Strategy

This pull request was tested by...

### TODO or Help Wanted

This pull request still needs...

### Build

- [ ] Ran `npm build`.

### Author

Signed-off-by: Your Name <Your Email@example.com>

2024-05-03 20:04 UTC, alexandruradovici requested changes
Please fill the pull request template?

2024-05-03 20:04 UTC, alexandruradovici commented on docs/project/2024/mihaela_raluca.dorobantu/index.md
> +**Author**: Mihaela-Raluca Dorobanțu
```suggestion
**Author**: Mihaela-Raluca Dorobanțu \
```

2024-05-03 20:04 UTC, alexandruradovici commented on docs/project/2024/mihaela_raluca.dorobantu/index.md
> +| [embedded-graphics](https://github.com/embedded-graphics/embedded-graphics) | 2D graphics library | Used for drawing to the display |
Do you need these libraries?

2024-05-03 20:04 UTC, alexandruradovici commented on docs/project/2024/mihaela_raluca.dorobantu/index.md
> +2. [link](https://example3.com)
Please add some links.

2024-05-04 19:05 UTC, alexandruradovici requested changes
Please fill the pull request template.

2024-05-04 19:05 UTC, alexandruradovici commented on docs/project/2024/mihaela_raluca.dorobantu/index.md
> +| [embedded-graphics](https://github.com/embedded-graphics/embedded-graphics) | 2D graphics library | Used for drawing to the display |
Do you need this library?

2024-05-05 07:43 UTC, alexandruradovici approved these changes

2024-05-05 11:35 UTC, DTeodor-Alexaandru approved these changes

2024-05-05 11:39 UTC, merged