Project documentation (carina.grec)
UPB-FILS-MA/upb-fils-ma.github.io pull request #171
Opened 2024-05-03 15:34 UTC by carinagrec

### Pull Request Overview

This pull request adds the documentation for the project House Thermometer.

### TODO or Help Wanted

This pull request still needs feedback.

### Author

Signed-off-by: Carina Grec <carina.grec@stud.fils.upb.ro>

2024-05-03 19:59 UTC, alexandruradovici requested changes

2024-05-03 19:59 UTC, alexandruradovici commented on docs/project/2024/carina.grec/index.md
> +![LED](https://github.com/carinagrec/upb-fils-ma.github.io/assets/150676040/9fe70bd8-0f70-42c2-90b6-aae9b26a2969)
Use the local file from this repository with a relative path.

2024-05-03 19:59 UTC, alexandruradovici commented on docs/project/2024/carina.grec/index.md
> +| [Raspberry Pi Pico W](https://www.optimusdigital.ro/en/raspberry-pi-boards/12394-raspberry-pi-pico-w.html) | The microcontroller with Wi-Fi capability, used for managing sensors and network communi
In the table, the first link is to wards the components description and the second link (the price) is to the store.

2024-05-03 19:59 UTC, alexandruradovici commented on docs/project/2024/carina.grec/LED.png
This image is with a big raspberry pi, not the pico.

2024-05-04 19:03 UTC, alexandruradovici requested changes

2024-05-04 19:03 UTC, alexandruradovici commented on docs/project/2024/carina.grec/LED (1).png
Please rename the file so that it does not use spaces and parentheses in its name.

2024-05-04 19:03 UTC, alexandruradovici commented on docs/project/2024/carina.grec/index.md
> +Connectivity and Interactions:
Please format this and make sure it displays correctly using `nom start`.

2024-05-04 19:03 UTC, alexandruradovici commented on docs/project/2024/carina.grec/index.md
> +<img src="LED (1).png">
Please us the markdown syntax for embedding images.

2024-05-04 19:03 UTC, alexandruradovici commented on docs/project/2024/carina.grec/index.md
> +| [embedded-graphics](https://github.com/embedded-graphics/embedded-graphics) | 2D graphics library | Utilized for drawing graphics and text on the display, including temperature data and visual indi
Do you need these libraries?

2024-05-04 19:03 UTC, alexandruradovici commented on docs/project/2024/carina.grec/index.md
> +5. https://www.tomshardware.com/how-to/oled-display-raspberry-pi-pico
Please add titles to your links.

2024-05-05 11:42 UTC, alexandruradovici requested changes

2024-05-05 11:42 UTC, alexandruradovici commented on docs/project/2024/carina.grec/LED (1).png
Please rename the file.

2024-05-05 11:48 UTC, alexandruradovici commented on docs/project/2024/carina.grec/index.md
> +<img src="LED (1).png">
This is not fixed.

2024-05-05 11:52 UTC, alexandruradovici requested changes

2024-05-05 11:52 UTC, alexandruradovici commented on docs/project/2024/carina.grec/index.md
> +![Architecture](docs/project/2024/carina.grec/architecture.png)
Please use a relative path.

2024-05-05 12:30 UTC, alexandruradovici requested changes

2024-05-05 12:30 UTC, alexandruradovici commented on docs/project/2024/carina.grec/index.md
> +**GitHub Project Link**: [link_to_github](https://github.com/UPB-FILS-MA/project-carinagrec)
```suggestion
**GitHub Project Link**: https://github.com/UPB-FILS-MA/project-carinagrec
```

2024-05-05 12:46 UTC, alexandruradovici commented on docs/project/2024/carina.grec/index.md
> +Raspberry Pi Pico W - a compact microcontroller board featuring the RP2040 chip and built-in Wi-Fi connectivity. It serves as the brain of the project, managing data collection from the temperature s
Are you sure that this is displayed correctly? Did you use `npm start` to look at it?

2024-05-05 12:46 UTC, alexandruradovici submitted a review, later dismissed

2024-05-05 12:54 UTC, alexandruradovici approved these changes

2024-05-05 17:02 UTC, TeodoraMiu submitted a review, later dismissed

2024-05-05 17:16 UTC, alexandruradovici approved these changes

2024-05-05 17:38 UTC, irina-b-dev approved these changes

2024-05-05 17:43 UTC, merged