Create index.md
UPB-FILS-MA/upb-fils-ma.github.io pull request #175
Opened 2024-05-03 17:10 UTC by IoanaP0711

### Pull Request Overview

This pull request adds/changes/fixes...

### Testing Strategy

This pull request was tested by...

### TODO or Help Wanted

This pull request still needs...

### Build

- [ ] Ran `npm build`.

### Author

Signed-off-by: Your Name <Your Email@example.com>

2024-05-03 19:49 UTC, alexandruradovici requested changes
Please fill pull request template.

2024-05-03 19:49 UTC, alexandruradovici commented on docs/project/2024/ioana.postelnecu/index.md
> +**Author**: POSTELNECU Ioana
```suggestion
**Author**: POSTELNECU Ioana \
```

2024-05-03 19:49 UTC, alexandruradovici commented on docs/project/2024/ioana.postelnecu/index.md
> +
Please add single line description of the project here.

2024-05-03 19:49 UTC, alexandruradovici commented on docs/project/2024/ioana.postelnecu/index.md
> +This project's architecture revolves around the Raspberry Pi Pico W as the microcontroller, executing the game code. The LCD screen 1602 module serves as the display interface for the game graphics.
A diagram would be good.

2024-05-04 10:44 UTC, alexandruradovici approved these changes

2024-05-04 18:40 UTC, irina-b-dev approved these changes

2024-05-04 18:59 UTC, alexandruradovici approved these changes

2024-05-04 18:59 UTC, alexandruradovici commented on docs/project/2024/ioana.postelnecu/Arhitechture.JPG
The spelling of the file name is incorrect :)

2024-05-04 19:03 UTC, merged