Project Update
UPB-FILS-MA/upb-fils-ma.github.io pull request #177
Opened 2024-05-03 17:40 UTC by MarioMario7

### Pull Request Overview

Adds the project of Iacobescu Cristian Mario to the main repository

### Author

Signed-off-by: Iacobescu Cristian Mario<mario.iacobescu@gmail.com>

2024-05-03 19:42 UTC, alexandruradovici requested changes

2024-05-03 19:42 UTC, alexandruradovici commented on docs/project/2024/cristian.iacobescu/index.md
> +| [core::fmt](https://doc.rust-lang.org/beta/core/fmt/index.html) | Utilities for formatting and printing strings. | Used to print floats and integers to the LCD|
```suggestion
```

This is part of the rust core library.

2024-05-04 10:43 UTC, alexandruradovici approved these changes

2024-05-04 18:41 UTC, irina-b-dev approved these changes

2024-05-04 18:45 UTC, merged