Add files via upload
UPB-FILS-MA/upb-fils-ma.github.io pull request #178
Opened 2024-05-03 18:21 UTC by RaduRadel

### Pull Request Overview

This pull request adds/changes/fixes...

### Testing Strategy

This pull request was tested by...

### TODO or Help Wanted

This pull request still needs...

### Build

- [ ] Ran `npm build`.

### Author

Signed-off-by: Your Name <Your Email@example.com>

2024-05-03 19:41 UTC, alexandruradovici requested changes
Please fill out the pull request template.

2024-05-03 19:41 UTC, alexandruradovici commented on docs/project/2024/Baccela Radu-Costin/index.md
> +![Solar Tracker System Diagram](diagram.png "Diagram of the Solar Tracker System")
This syntax is incorrect, please try it with `npm start`.

2024-05-03 19:41 UTC, alexandruradovici commented on docs/project/2024/Baccela Radu-Costin/index.md
> +4. [link](https://www.youtube.com/watch?v=lrugreN2K4w)
Please add the link titles.

2024-05-03 19:52 UTC, alexandruradovici requested changes

2024-05-03 19:52 UTC, alexandruradovici commented on docs/project/2024/Baccela Radu-Costin/diagram.png
Rename the folder to your curs.upb.ro username.

2024-05-04 10:36 UTC, alexandruradovici commented
> Please fill out the pull request template.

This is  ot resolved.

2024-05-04 15:02 UTC, RaduRadel commented
> > Please fill out the pull request template.
> 
> This is not resolved.

2024-05-04 18:56 UTC, alexandruradovici commented on docs/project/2024/radu_costin.baccela/index.md
> +| [embedded-graphics](https://github.com/embedded-graphics/embedded-graphics) | 2D graphics library | Used for drawing to the display |
Do you need this library?

2024-05-04 19:18 UTC, alexandruradovici approved these changes

2024-05-04 19:21 UTC, irina-b-dev approved these changes

2024-05-04 19:30 UTC, merged