Project documentation TempTune
UPB-FILS-MA/upb-fils-ma.github.io pull request #182
Opened 2024-05-04 00:37 UTC by Gabriel-x-1

### Pull Request Overview

This pull request adds/changes/fixes...

### Testing Strategy

This pull request was tested by...

### TODO or Help Wanted

This pull request still needs...

### Build

- [ ] Ran `npm build`.

### Author

Signed-off-by: Your Name <Your Email@example.com>

2024-05-04 10:31 UTC, alexandruradovici reviewed
Isn't this a duplicate?

2024-05-04 12:07 UTC, Gabriel-x-1 commented
TempTune is a team project, i am collaborating with Pica Eduard on this. Should we make a single pull request?

2024-05-04 18:49 UTC, alexandruradovici requested changes
This is the only PR that you sent for this project, right?

2024-05-04 18:49 UTC, alexandruradovici commented on docs/project/2024/gabriel.bilciurescu/index.md
> +| [18650 LI-ION Battery 3200mA 10A Panasonic]() |  Battery | [23 RON](https://www.emag.ro/acumulator-18650-li-ion-3200ma-10a-panasonic-lincr18650bd/pd/DL86WWBBM/) |
The link is missing here.

2024-05-04 18:49 UTC, alexandruradovici commented on docs/project/2024/gabriel.bilciurescu/arhitecture.png
Rename the folder with both of your usernames with _ between them.

2024-05-04 18:49 UTC, alexandruradovici commented
Add another Signed-off line to the pull request description with the second name and email.

2024-05-04 18:50 UTC, alexandruradovici commented
> TempTune is a team project, i am collaborating with Pica Eduard on this. Should we make a single pull request?

Yes

2024-05-04 19:29 UTC, Gabriel-x-1 commented
solved the requested changes

2024-05-04 20:16 UTC, alexandruradovici approved these changes

2024-05-05 11:36 UTC, DTeodor-Alexaandru approved these changes

2024-05-05 11:41 UTC, merged