submit documentation
UPB-FILS-MA/upb-fils-ma.github.io pull request #184
Opened 2024-05-04 01:17 UTC by 12mihai05

### Pull Request Overview

This pull request adds the Project Documentation for the Music Player.

### TODO or Help Wanted

This pull request contains my project's documentation.
Further modifications of the documentation will be uploaded here.

### Author

Signed-off-by: Pasaroiu Mihai Octavian <pasaroiumihai@yahoo.com>

2024-05-04 10:28 UTC, alexandruradovici requested changes
Please fill the pull request template.

2024-05-04 10:28 UTC, alexandruradovici commented on docs/project/2024/mihai.pasaroiu/index.md
> +| [embedded-graphics](https://github.com/embedded-graphics/embedded-graphics) | 2D graphics library | Used for drawing to the display |
Do you need these libraries?

2024-05-04 10:28 UTC, alexandruradovici commented on docs/project/2024/mihai.pasaroiu/index.md
> +2. [link](https://example3.com)
Please add some links for your project.

2024-05-04 18:41 UTC, alexandruradovici commented on docs/project/2024/mihai.pasaroiu/Arhitecture.png
The spelling is wrong for this file name :)

2024-05-04 18:42 UTC, alexandruradovici requested changes
Please fill the pull request template.

2024-05-04 20:14 UTC, alexandruradovici approved these changes

2024-05-05 11:37 UTC, DTeodor-Alexaandru approved these changes

2024-05-05 11:42 UTC, merged