iulia.buta
UPB-FILS-MA/upb-fils-ma.github.io pull request #188
Opened 2024-05-04 10:07 UTC by ButaIulia

### Pull Request Overview

This pull request adds the Project Documentation for Fire Alarm.

### TODO or Help Wanted

This pull request is still a draft.Further modifications of the documentation will be uploaded here.

### Author

Signed-off-by: Iulia Buta <iuliamirelabuta@gmail.com>

2024-05-04 10:19 UTC, alexandruradovici requested changes

2024-05-04 10:19 UTC, alexandruradovici commented on docs/project/2024/iulia_mirela.buta/index.md
> +| ------------------------------------------------------------------------------------------------------- | ------------------- | ---------------------------------------------------------------------
```suggestion
|-|-|-|
```

2024-05-04 10:19 UTC, alexandruradovici commented on docs/project/2024/iulia_mirela.buta/index.md
> +| ---------------------------------------- | ---------------------------------- | ---------------------------------- |
```suggestion
|-|-|-|
```

2024-05-04 10:19 UTC, alexandruradovici commented on docs/project/2024/iulia_mirela.buta/index.md
> +| [st7789] | Display driver for st7789 | Used for the display for Pico Explorer |
Do you need this library?

2024-05-04 10:19 UTC, alexandruradovici commented on docs/project/2024/iulia_mirela.buta/index.md
> +| [Rust](https://www.rust-lang.org/)       | Programming Language               | Programming Language               |
Rust is not a library.

2024-05-04 10:19 UTC, alexandruradovici commented on docs/project/2024/iulia_mirela.buta/index.md
> +| [embedded-graphics]         | 2D graphics library                         | Used for drawing to the display
Do you need this library?

2024-05-04 10:19 UTC, alexandruradovici commented on docs/project/2024/iulia_mirela.buta/index.md
> +*Author*: Buta Iulia-Mirela
```suggestion
*Author*: Buta Iulia-Mirela \
```

2024-05-04 10:19 UTC, alexandruradovici commented on docs/project/2024/iulia_mirela.buta/index.md
> +
Add a one line description of your project.

2024-05-04 10:47 UTC, alexandruradovici requested changes

2024-05-04 10:47 UTC, alexandruradovici commented on docs/project/2024/iulia_mirela.buta/index.md
> + +---------+           +-----------+
````suggestion
```
+-------------------------+
 |      Fire Sensor        |
 +-------------------------+

                 |
                 | (Signal)
                 V
         +-----------------+
         | Raspberry Pi Pico|
         +-----------------+
                 |
      +----------+----------+
      |                     |
      V                     V
 +---------+           +-----------+
 |  Buzzer |           |  ST7789   |
 +---------+           +-----------+
```
````

2024-05-04 10:47 UTC, alexandruradovici commented on docs/project/2024/iulia_mirela.buta/index.md
> +| [Rapspberry Pi Pico](https://www.raspberrypi.com/documentation/microcontrollers/raspberry-pi-pico.html) | The microcontroller | [39 RON](https://www.optimusdigital.ro/en/raspberry-pi-boards/12394-r
Please add a link to all the parts.

2024-05-04 10:47 UTC, alexandruradovici commented on docs/project/2024/iulia_mirela.buta/index.md
> +| [VsCode](https://code.visualstudio.com/) | Integrated Development Environment | Integrated Development Environment |
```suggestion     
```

VS Code is not a library.

2024-05-04 10:58 UTC, alexandruradovici requested changes

2024-05-04 10:58 UTC, alexandruradovici commented on docs/project/2024/iulia_mirela.buta/index.md
> +-+-------------------------+
This for sure does not render corectly, please test it, you are missing a ```.

2024-05-04 16:47 UTC, alexandruradovici requested changes

2024-05-04 16:47 UTC, alexandruradovici commented on docs/project/2024/iulia_mirela.buta/index.md
> ++      +----------+----------+
This is not correct and does not render, this is the git diff that the website shows. You can clock click *Commit Changes* and it makes the modifications. Please make the ascii chart enclosed in ```.

2024-05-04 16:47 UTC, alexandruradovici commented on docs/project/2024/iulia_mirela.buta/index.md
> +| [Rapspberry Pi Pico](https://www.raspberrypi.com/documentation/microcontrollers/raspberry-pi-pico.html) | The microcontroller | [39 RON](https://www.optimusdigital.ro/en/raspberry-pi-boards/12394-r
Links are still missing and the square bracket are not useful.

2024-05-04 16:47 UTC, alexandruradovici commented on docs/project/2024/iulia_mirela.buta/index.md
> +2. https://www.youtube.com/watch?v=y1_scz9I0go
Please use the proper markdown links syntax.

2024-05-04 20:13 UTC, alexandruradovici requested changes

2024-05-04 20:13 UTC, alexandruradovici commented on docs/project/2024/iulia_mirela.buta/index.md
> +         +---------+           +-----------+
````suggestion
```
+-------------------------+
|      Fire Sensor        |
+-------------------------+

                         |
                         | (Signal)
                         V
                 +-----------------+
                 | Raspberry Pi Pico|
                 +-----------------+
                         |
              +----------+----------+
              |                     |
              V                     V
         +---------+           +-----------+
         |  Buzzer |           |  ST7789   |
         +---------+           +-----------+
```
````

2024-05-04 20:13 UTC, alexandruradovici commented on docs/project/2024/iulia_mirela.buta/index.md
> +         +---------+           +-----------+
Use *Commit suggestion* to merge this and then udate your branch with `git pull`.

2024-05-04 20:26 UTC, alexandruradovici approved these changes
No architecture diagram?

2024-05-04 20:33 UTC, ButaIulia commented
> No architecture diagram?

It's not the one that I put already? With the arrows and how are connected between them?

2024-05-05 12:53 UTC, DanutAldea approved these changes

2024-05-05 12:54 UTC, irina-nita approved these changes

2024-05-05 15:05 UTC, merged