Draft Project documentation (mihai.tigaeru)
UPB-FILS-MA/upb-fils-ma.github.io pull request #190
Opened 2024-05-04 10:59 UTC by septimium

### Pull Request Overview

This draft pull request adds the index.md file to the project folder.

### Testing Strategy

Draft

### TODO or Help Wanted

Draft

### Build

- [ ] Ran `npm build`.

### Author

Signed-off-by: Mihai-Septimiu Tigaeru <septimiutg@gmail.com>

2024-05-04 12:19 UTC, septimium commented
Is there anything I should modify besides the Architecture?

2024-05-04 16:43 UTC, alexandruradovici requested changes

2024-05-04 16:43 UTC, alexandruradovici commented on docs/project/2024/mihai.tigaeru/index.md
> +**GitHub Project Link**: (https://github.com/UPB-FILS-MA/project-septimium)
```suggestion
**GitHub Project Link**: https://github.com/UPB-FILS-MA/project-septimium
```

2024-05-04 16:43 UTC, alexandruradovici commented on docs/project/2024/mihai.tigaeru/index.md
> +| Breadboard 830 | Hardware Pins Connections | [9 RON](https://www.bitmi.ro/componente-electronice/breadboard-830-puncte-mb-102-10500.html) |
Please add links to the devices, not just the store where you buy them.

2024-05-04 18:16 UTC, septimium commented
Is it ok now?

2024-05-04 18:37 UTC, alexandruradovici approved these changes

2024-05-04 18:37 UTC, alexandruradovici commented
Yes

2024-05-05 12:54 UTC, DanutAldea approved these changes

2024-05-05 12:59 UTC, merged