Added my project
UPB-FILS-MA/upb-fils-ma.github.io pull request #194
Opened 2024-05-04 13:54 UTC by CearceafAlb

2024-05-04 16:37 UTC, alexandruradovici commented on docs/project/2024/robert.leonte/index.md
> +| [Breadboard(taken from a kit)] | The base | [54 EUR(the entire kit)](https://www.amazon.de/gp/product/B01II76PDM/ref=ox_sc_act_title_1?smid=AZF7WYXU5ZANW&psc=1) |
No square brackets if here is no link. Please do add links to your components.

2024-05-04 16:37 UTC, alexandruradovici commented on docs/project/2024/robert.leonte/index.md
> +| [embedded-graphics](https://github.com/embedded-graphics/embedded-graphics) | 2D graphics library | Used for drawing to the display |
Do you need these libraries?

2024-05-04 16:37 UTC, alexandruradovici commented on docs/project/2024/robert.leonte/index.md
> +2. [link](https://example3.com)
Please add links for your project.

2024-05-05 16:57 UTC, alexandruradovici requested changes
Please fill the pull request description following the template.

2024-05-05 16:57 UTC, alexandruradovici commented on docs/project/2024/robert.leonte/index.md
> +1. [link](https://learn.microsoft.com/en-us/gaming/gdk/_content/gc/input/overviews/input-overview)
Please add a title to the link.

2024-05-05 16:58 UTC, alexandruradovici requested changes
Please fill the pull request description following the template.

2024-05-05 16:59 UTC, CearceafAlb reviewed
Made the changes

2024-05-05 19:53 UTC, CearceafAlb commented
Apologies, I have added it now. Hope everything is ok.

2024-05-05 19:55 UTC, alexandruradovici requested changes

2024-05-05 19:55 UTC, alexandruradovici commented on docs/project/2024/robert.leonte/index.md
> +1. [link](https://learn.microsoft.com/en-us/gaming/gdk/_content/gc/input/overviews/input-overview)
Not resolved.

2024-05-05 19:56 UTC, CearceafAlb reviewed
Added the title to the link.

2024-05-05 19:57 UTC, alexandruradovici approved these changes

2024-05-05 20:02 UTC, irina-nita approved these changes

2024-05-05 20:07 UTC, merged