documentation
UPB-FILS-MA/upb-fils-ma.github.io pull request #197
Opened 2024-05-04 14:56 UTC by msrgq

project documentation

### Pull Request Overview

This pull request adds the documentation of my project

### TODO or Help Wanted

Please let me know if there is anything that needs changes

### Author

Signed-off-by: Surugiu Monica <msurugiu1301@gmail.com>

2024-05-04 16:35 UTC, alexandruradovici approved these changes

2024-05-04 16:47 UTC, TeodoraMiu approved these changes

2024-05-04 17:17 UTC, msrgq commented
what should i do if the test deployment failed?

2024-05-04 18:29 UTC, alexandruradovici requested changes
Linux is case sensitive. 

Please rename the architecture file to reflect a correct spelling.

2024-05-04 18:29 UTC, alexandruradovici commented on docs/project/2024/ioana.surugiu/index.md
> +![Architechture Diagram](arhitecture_schematic.JPG)
```suggestion
![Architecture Diagram](arhitecture_schematic.jpg)
```

2024-05-04 20:11 UTC, alexandruradovici approved these changes

2024-05-05 12:55 UTC, DanutAldea approved these changes

2024-05-05 13:00 UTC, merged