Documentation
UPB-FILS-MA/upb-fils-ma.github.io pull request #198
Opened 2024-05-04 15:45 UTC by George2543

### Pull Request Overview

This pull request adds the documentation of my project

### TODO or Help Wanted

Maybe this pull request still needs modifications.

### Build

### Author

Signed-off-by: Radu George-Alexandru <georgeradu642@gmail.com>

2024-05-04 16:34 UTC, alexandruradovici requested changes

2024-05-04 16:34 UTC, alexandruradovici commented on docs/project/2024/george.radu2504/index.md
> +**Author**: Radu George-Alexandru
```suggestion
**Author**: Radu George-Alexandru \
```

2024-05-04 20:10 UTC, alexandruradovici requested changes

2024-05-04 20:10 UTC, alexandruradovici commented on docs/project/2024/george.radu2504/index.md
> +**GitHub Project Link**: https://github.com/UPB-FILS-MA/project-George2543
```suggestion
**Author**: Radu George-Alexandru \
**GitHub Project Link**: https://github.com/UPB-FILS-MA/project-George2543
```

2024-05-04 20:10 UTC, alexandruradovici commented on docs/project/2024/george.radu2504/index.md
> +![Rasberry Pi Pico W (5)](https://github.com/George2543/upb-fils-ma.github.io/assets/154756379/599a908e-feed-4ca3-8aa4-25665cae1950)
Please use the picture from this repository.

2024-05-04 20:10 UTC, alexandruradovici commented on docs/project/2024/george.radu2504/index.md
> +2. [YouTube](https://www.youtube.com/watch?v=OapZNPaKrmA&ab_channel=ElectronicsUniversity)
Write the video titles in the links title.

2024-05-04 20:21 UTC, alexandruradovici approved these changes

2024-05-05 12:54 UTC, irina-nita approved these changes

2024-05-05 15:05 UTC, merged