Added one line description
UPB-FILS-MA/upb-fils-ma.github.io pull request #203
Opened 2024-05-04 17:27 UTC by anamaria2004

### Pull Request Overview

This pull request adds one line description.

### Testing Strategy

This pull request was tested by Ana-Maria Comeaga

### TODO or Help Wanted

This pull request needs to be checked

### Build

- [ ] Ran `npm build`.

### Author

Signed-off-by: Ana-Maria Comeaga <anamariacomeaga@yahoo.com>

2024-05-04 17:50 UTC, anamaria2004 commented
What should I do to make it functional?

2024-05-04 18:05 UTC, alexandruradovici approved these changes

2024-05-04 18:05 UTC, alexandruradovici requested changes
Please fix the info box by adding a \ (newline) after your name.

2024-05-04 20:06 UTC, alexandruradovici requested changes

2024-05-04 20:06 UTC, alexandruradovici commented on docs/project/2024/ana_maria.comeaga/index.md
>  **GitHub Project Link**: https://github.com/UPB-FILS-MA/project-anamaria2004
```suggestion
**Author**: Ana-Maria Comeaga \
**GitHub Project Link**: https://github.com/UPB-FILS-MA/project-anamaria2004
```

2024-05-04 20:26 UTC, alexandruradovici approved these changes

2024-05-05 17:07 UTC, TeodoraMiu approved these changes

2024-05-05 17:12 UTC, merged