Project documentation
UPB-FILS-MA/upb-fils-ma.github.io pull request #209
Opened 2024-05-04 19:18 UTC by VladVulturescu

### Pull Request Overview

This pull request adds the project documentation for Vlad Vulturescu

### Testing Strategy

This pull request was tested by Vlad Vulturescu

### TODO or Help Wanted

This pull request still needs to be checked and verified

### Build

- [ ] Ran `npm build`.

### Author

Signed-off-by: Vlad Vulturescu <vlad.vulturescu@yahoo.com>

2024-05-04 19:21 UTC, alexandruradovici requested changes

2024-05-04 19:21 UTC, alexandruradovici commented on docs/project/2024/vlad.vulturescu/index.md
> +| [Breadboard]() | The basis for the project | [10 RON](https://www.optimusdigital.ro/ro/prototipare-breadboard-uri/8-breadboard-830-points.html?search_query=breadboard&results=144) |
missing links

2024-05-04 20:06 UTC, alexandruradovici requested changes

2024-05-04 20:06 UTC, alexandruradovici commented on docs/project/2024/vlad.vulturescu/index.md
> +| [embedded-graphics](https://github.com/embedded-graphics/embedded-graphics) | 2D graphics library | Used for drawing to the display |
Do you need these libraries?

2024-05-04 20:17 UTC, alexandruradovici approved these changes

2024-05-05 17:05 UTC, TeodoraMiu approved these changes

2024-05-05 17:16 UTC, merged