Ferrari Line Follower and Obstacle Avoider Car
UPB-FILS-MA/upb-fils-ma.github.io pull request #222
Opened 2024-05-04 20:34 UTC by IonescuMariaMagdalena

### Pull Request Overview

This pull request fixes the documentation

### Testing Strategy

This pull request was tested by...

### TODO or Help Wanted

This pull request still needs to be reviewed

### Build

- [ ] Ran `npm build`.

### Author

Signed-off-by: Ionescu Maria-Magdalena <maria.ionescu0511@stud.fils.upb.ro>

2024-05-04 20:36 UTC, alexandruradovici requested changes

2024-05-04 20:36 UTC, alexandruradovici commented on docs/project/2024/maria.ionescu/index.md
> +- The Raspberry Pi Pico W is a microcontroller board based on the RP2040 microcontroller chip developed by Raspberry Pi, that manages the project's operations, controlling the servo motor, processing
```suggestion
 - The Raspberry Pi Pico W is a microcontroller board based on the RP2040 microcontroller chip developed by Raspberry Pi, that manages the project's operations, controlling the servo motor, processing sensor data, and handling other components.
```
Indent one for a list item.

2024-05-04 20:36 UTC, alexandruradovici commented on docs/project/2024/maria.ionescu/index.md
> +Pin headers
These will be all displayed on a single line.

2024-05-04 20:38 UTC, alexandruradovici commented
Why a new PR?

2024-05-04 21:17 UTC, IonescuMariaMagdalena commented
I updated the index.md. By mistake, I've submitted a new pull request, I apologize

2024-05-05 07:44 UTC, alexandruradovici approved these changes

2024-05-05 07:45 UTC, alexandruradovici requested changes

2024-05-05 07:45 UTC, alexandruradovici commented on docs/project/2024/maria.ionescu/architecture.jpg
Please use the images in the *index.md* file.

2024-05-05 11:06 UTC, alexandruradovici requested changes

2024-05-05 11:06 UTC, alexandruradovici commented on docs/project/2024/maria.ionescu/index.md
> +
Please add a one line description of your project,

2024-05-05 11:53 UTC, alexandruradovici approved these changes

2024-05-05 12:52 UTC, irina-nita approved these changes

2024-05-05 12:59 UTC, merged