Project Documentation Stoica Stefan Nicolae
UPB-FILS-MA/upb-fils-ma.github.io pull request #223
Opened 2024-05-04 20:46 UTC by bep1s69

### Pull Request Overview

This pull request the project documentation for Stoica Stefan Nicolae

### Author

Signed-off-by: Your Name <stoicastef27@gmail.com>

2024-05-04 20:50 UTC, alexandruradovici commented
Please write your name in the pull request description.

2024-05-04 20:51 UTC, alexandruradovici requested changes

2024-05-04 20:51 UTC, alexandruradovici commented on docs/project/2024/stefan.stoica2706/index.md
> +**GitHub Project Link**: https://github.com/UPB-FILS-MA/project-bep1s69
```suggestion
:::info

**Author**: Stoica Stefan Nicolae \
**GitHub Project Link**: https://github.com/UPB-FILS-MA/project-bep1s69

:::
```

2024-05-04 20:51 UTC, alexandruradovici commented on docs/project/2024/stefan.stoica2706/index.md
> +Control Interface
````suggestion
```
[Main Components]
|
+-----+-----+
|           |
Temperature   Light
Sensor        Sensor
|           |
Raspberry Pi Pico ----------- WiFi Module
|           |                   |
Motor       LED             Web Server
(Fan)     (Variable Intensity)   |
Control Interface
```
````

2024-05-04 20:51 UTC, alexandruradovici commented on docs/project/2024/stefan.stoica2706/index.md
> +| [esp-rs](https://github.com/esp-rs) | Wi-Fi driver | Used for the Wi-Fi connectivity |
This will not work with the Raspberry Pi Pico.

2024-05-05 11:04 UTC, alexandruradovici approved these changes

2024-05-05 12:59 UTC, merged

2024-05-05 12:59 UTC, ZamfirAndreiPaul approved these changes