Project documentation
UPB-FILS-MA/upb-fils-ma.github.io pull request #269
Opened 2024-05-06 09:39 UTC by alecsandraiordache

### Pull Request Overview

This pull request has an update of the project.

### Testing Strategy

This pull request was tested by...

### TODO or Help Wanted

This pull request is an update. I will update the further modification.

### Build

- [ ] Ran `npm build`.

### Author

Signed-off-by: Alecsandra-Elena Iordache <alecsandra.iordache@yahoo.com> <alecsandra.iordache@stud.fils.upb.ro>

2024-05-06 09:55 UTC, alexandruradovici commented
Duplicate of #268.

2024-05-06 22:26 UTC, alexandruradovici requested changes

2024-05-06 22:26 UTC, alexandruradovici commented on docs/project/2024/alecsandra_elena.iordache/index.md
> +•	MG996 Servo Motor
Please use the markdown syntax for lists.

2024-05-10 12:30 UTC, alexandruradovici commented
@alecsandraiordache is this still in progress?

2024-05-10 13:37 UTC, alexandruradovici commented on docs/project/2024/alecsandra_elena.iordache/index.md
> +a.   Raspberry Pi Pico
Does this render correctly?

2024-05-10 13:39 UTC, alecsandraiordache commented on docs/project/2024/alecsandra_elena.iordache/index.md
> +a.   Raspberry Pi Pico
Yes

2024-05-19 09:43 UTC, alexandruradovici requested changes

2024-05-19 09:43 UTC, alexandruradovici commented on .idea/.name
Delete this folder

2024-05-19 09:43 UTC, alexandruradovici commented on docs/project/2024/alecsandra_elena.iordache/Photo of the robot.jpg
Please do not use spaces in the file names.

2024-05-19 13:17 UTC, alexandruradovici approved these changes

2024-05-19 14:16 UTC, TeodoraMiu approved these changes

2024-05-19 15:48 UTC, alexandruradovici approved these changes

2024-05-19 15:48 UTC, alexandruradovici requested changes
Please move the kicad files to your project's repository.

2024-05-19 22:46 UTC, alexandruradovici commented
@alecsandraiordache please solve the issues so we can merge this.

2024-05-20 07:09 UTC, alecsandraiordache commented
> @alecsandraiordache please solve the issues so we can merge this.

Is it ok now?

2024-05-20 11:14 UTC, alexandruradovici approved these changes

2024-05-20 11:19 UTC, TeodoraMiu approved these changes

2024-05-20 11:25 UTC, merged