Added the KiCad schematics and some updates for the documentation
UPB-FILS-MA/upb-fils-ma.github.io pull request #288
Opened 2024-05-15 20:08 UTC by istudormihai

### Pull Request Overview

This pull request adds the KiCad schematics and some changes to the documentation.

### TODO or Help Wanted

This pull request still needs verification.

### Author

Signed-off-by: Istudor Victor-Mihai <istudor9@gmail.com>

2024-05-17 15:07 UTC, alexandruradovici requested changes
Please move the kicad files to your project repository.

2024-05-17 17:08 UTC, istudormihai commented
> Please move the kicad files to your project repository.

I moved it and also updated the Log section.

2024-05-18 12:14 UTC, alexandruradovici approved these changes

2024-05-18 12:24 UTC, ZamfirAndreiPaul approved these changes

2024-05-18 12:31 UTC, merged