finished up hardware milestone + fixes
UPB-FILS-MA/upb-fils-ma.github.io pull request #291
Opened 2024-05-17 09:17 UTC by domnudragota

### Pull Request Overview

This pull request completes the hardware part from last week

### Testing Strategy

This pull request was tested by me

### TODO or Help Wanted

This pull request still needs the software part

### Build

- [ ] Ran `npm build`.

### Author

Signed-off-by: Andrei Dragota <anditu2003@gmail.com>

2024-05-17 15:06 UTC, alexandruradovici requested changes
Please move the kicad files to your project repository.

2024-05-17 15:23 UTC, domnudragota commented
Besides the schematic file, do I need to add anything else to the project repo ? (ex. library files, whole project file in KiCad) ?

2024-05-18 12:12 UTC, alexandruradovici commented
We have to ne able to open your project in kicad.

2024-05-18 12:12 UTC, alexandruradovici approved these changes

2024-05-18 12:26 UTC, ZamfirAndreiPaul approved these changes

2024-05-18 12:31 UTC, merged