hardware_remote_game(miruna.solomon)
UPB-FILS-MA/upb-fils-ma.github.io pull request #293
Opened 2024-05-17 14:03 UTC by mirusol

Pull Request Overview
This pull request adds the documentation for the Remote Game

TODO or Help Wanted
This pull request still needs to be evaluated

Author
Signed-off-by: Solomon Miruna solomonmiruna65@yahoo.com

2024-05-17 15:04 UTC, alexandruradovici approved these changes

2024-05-18 12:11 UTC, alexandruradovici requested changes
Pleaee move the kicad project files to your project's repository.

2024-05-19 08:03 UTC, alexandruradovici approved these changes

2024-05-19 12:26 UTC, ZamfirAndreiPaul approved these changes

2024-05-19 13:23 UTC, merged