Lecture 10
UPB-FILS-MA/upb-fils-ma.github.io pull request #295
Opened 2024-05-17 15:03 UTC by alexandruradovici

### Pull Request Overview

This pull request adds the slides for lecture 10.

### Testing Strategy

This pull request was tested by using the slides.

### TODO or Help Wanted

Feedback

### Build

- [x] Ran `npm build`.

### Author

Signed-off-by: Alexandru Radovici <alexandru.radovici@wyliodrin.com>

2024-05-17 15:39 UTC, DanutAldea requested changes

2024-05-17 15:39 UTC, DanutAldea commented on slides/lectures/10/os/slides.md
> +- peripherals a viewed as files (*POSIX*)
```suggestion
- peripherals are viewed as files (*POSIX*)
```

2024-05-17 15:39 UTC, DanutAldea commented on slides/lectures/10/rtos/slides.md
> +- **real time** means **performing** an action in **always** in a **deterministic** amount of **time**
```suggestion
- **real time** means **performing** an action **always** in a **deterministic** amount of **time**
```

2024-05-17 15:39 UTC, DanutAldea commented on slides/lectures/10/tock/slides.md
> +- **Microkernel** architecture
```suggestion
- **Hybrid** architecture
```
Is Tock not a hybrid architecture?

2024-05-17 15:39 UTC, DanutAldea commented on slides/lectures/10/tock/slides.md
> +- *start* and *stop* are use commands
```suggestion
- *start* and *stop* are user commands
```

2024-05-17 15:39 UTC, DanutAldea commented on slides/lectures/10/tock/slides.md
> +  - trying to perform operations
```suggestion
  - trying to perform privileged operations
```

2024-05-18 12:29 UTC, ZamfirAndreiPaul approved these changes

2024-05-19 20:31 UTC, DanutAldea approved these changes

2024-05-19 20:33 UTC, ZamfirAndreiPaul approved these changes

2024-05-19 20:41 UTC, merged