Hardware Milestone
UPB-FILS-MA/upb-fils-ma.github.io pull request #301
Opened 2024-05-17 18:12 UTC by MarioMario7

### Pull Request Overview

This pull request adds the changes needed for the hardware milestone

### Author

Signed-off-by: Iacobescu Cristian Mario<iacobescucm@gmail.com>

2024-05-18 12:01 UTC, alexandruradovici requested changes

2024-05-18 12:01 UTC, alexandruradovici commented on docs/project/2024/cristian.iacobescu/kiCADProj.kicad_sch
Please move this file to your project's repository.

2024-05-19 08:04 UTC, alexandruradovici approved these changes

2024-05-19 08:53 UTC, alexandruradovici approved these changes

2024-05-19 12:28 UTC, ZamfirAndreiPaul approved these changes

2024-05-19 12:34 UTC, merged