Project documentation
UPB-FILS-MA/upb-fils-ma.github.io pull request #303
Opened 2024-05-17 19:35 UTC by 12mihai05

### Pull Request Overview

This pull request adds the hardware description and kicad schematics.

### Author

Signed-off-by: Pasaroiu Mihai <pasaroiumihai@yahoo.com>

2024-05-18 11:59 UTC, alexandruradovici requested changes

2024-05-18 11:59 UTC, alexandruradovici commented on docs/project/2024/mihai.pasaroiu/project.kicad_sch
Please move this file to your project repository.

2024-05-18 17:29 UTC, 12mihai05 commented on docs/project/2024/mihai.pasaroiu/project.kicad_sch
i moved it.

2024-05-19 08:06 UTC, alexandruradovici commented on docs/project/2024/mihai.pasaroiu/project.kicad_sch
The file is still in this branch.

2024-05-19 13:45 UTC, alexandruradovici submitted a review, later dismissed

2024-05-19 13:46 UTC, 12mihai05 commented on docs/project/2024/mihai.pasaroiu/project.kicad_sch
i removed it, also i have a question do we need to put images with the build of the hardware, not only the schematic, in the documentation?

2024-05-19 13:49 UTC, 12mihai05 commented
do i need to put images in the documentation with the build hardware, not only the schematics in kicad?

2024-05-19 13:51 UTC, alexandruradovici commented
Yes, please put some images.

2024-05-19 17:53 UTC, alexandruradovici submitted a review, later dismissed

2024-05-19 17:53 UTC, alexandruradovici commented
Please fix the conflicts.

2024-05-19 18:10 UTC, alexandruradovici approved these changes

2024-05-19 18:19 UTC, alexandruradovici approved these changes

2024-05-19 19:16 UTC, TeodoraMiu approved these changes

2024-05-19 19:22 UTC, merged