Kalman filter alert system project documentation
UPB-FILS-MA/upb-fils-ma.github.io pull request #304
Opened 2024-05-17 20:09 UTC by economuteo

### Pull Request Overview

This pull request adds/changes/fixes...

### Testing Strategy

This pull request was tested by...

### TODO or Help Wanted

This pull request still needs...

### Build

- [ ] Ran `npm build`.

### Author

Signed-off-by: Your Name <Your Email@example.com>

2024-05-19 18:33 UTC, kaanmeister commented
Fill the pull request template and KiCad folder has to be in your project repository not here.

2024-05-19 19:09 UTC, alexandruradovici commented
Please fix the conflicts.

2024-05-19 19:44 UTC, alexandruradovici commented
Please fill the pull request template.

2024-05-19 19:51 UTC, economuteo commented
> Please fill the pull request template.

Is it ok now? I filled it!

2024-05-19 19:52 UTC, alexandruradovici requested changes

2024-05-19 19:52 UTC, alexandruradovici commented on .anima/.gitignore
Please delete this.

2024-05-19 19:58 UTC, economuteo commented on .anima/.gitignore
I deleted it

2024-05-20 06:55 UTC, alexandruradovici commented on .anima/.gitignore
The .idea folder is still here.

2024-05-20 06:58 UTC, ZamfirAndreiPaul approved these changes

2024-05-20 07:35 UTC, economuteo commented on .anima/.gitignore
> The .idea folder is still here.

I checked every folder in my project and now everything seems ok. I committed everything again. I hope it's ok now!

2024-05-20 07:43 UTC, economuteo commented on .anima/.gitignore
I wrote you a message on Teams about a problem that I'm facing right now.

2024-05-20 14:22 UTC, alexandruradovici requested changes

2024-05-20 14:22 UTC, alexandruradovici commented on .github/PULL_REQUEST_TEMPLATE.md
Please do not edit this file. This is the template that will be added to all pull requests' descriptions. Please edit the pull request description in github's interface.

2024-05-20 14:22 UTC, alexandruradovici commented on docs/project/index.md
Please do not edit this file.

2024-05-20 18:41 UTC, alexandruradovici requested changes

2024-05-20 18:41 UTC, alexandruradovici commented on .github/PULL_REQUEST_TEMPLATE.md
Please reset the file to the original.

2024-05-20 18:41 UTC, alexandruradovici commented on docs/project/2024/maria-irina.fotescu_teo-antonio.economu/index.md
> -:::
Please do not delete this line.

2024-05-20 18:41 UTC, alexandruradovici commented on docs/project/index.md
Please reset this file to the original.

2024-05-20 19:27 UTC, Fote20003 commented
Is it ok, now?

2024-05-20 20:15 UTC, economuteo commented
Is it ok now?

2024-05-20 20:40 UTC, alexandruradovici commented
Please take a look at the changed files, the files still have modifications. Please copy and paste the original files.

2024-05-20 20:44 UTC, closed without merging

2024-05-20 21:09 UTC, Fote20003 commented
Is it ok now?