Hardware
UPB-FILS-MA/upb-fils-ma.github.io pull request #306
Opened 2024-05-17 21:21 UTC by alexandra214

### Pull Request Overview

This pull request adds the documentation for the Clock-in project.

### TODO or Help Wanted

Please let me know if there is anything to change.

### Author

Signed-off-by: Oblu Alexandra Mihaela oblu.alexandra@proton.me

2024-05-18 11:56 UTC, alexandruradovici requested changes

2024-05-18 11:56 UTC, alexandruradovici commented on docs/project/2024/alexandra.oblu/alexandra.oblu.md
Please edit index.md instead of adding a new file.

2024-05-18 16:03 UTC, alexandra214 commented on docs/project/2024/alexandra.oblu/alexandra.oblu.md
I fixed it.

2024-05-19 08:12 UTC, alexandruradovici requested changes

2024-05-19 08:12 UTC, alexandruradovici commented on docs/project/2024/alexandra.oblu/index.md
> +**GitHub Project Link**: [Clock-in](https://github.com/UPB-FILS-MA/project-alexandra214)
```suggestion
**GitHub Project Link**: https://github.com/UPB-FILS-MA/project-alexandra214
```

2024-05-19 09:53 UTC, alexandra214 commented on docs/project/2024/alexandra.oblu/index.md
> +**GitHub Project Link**: [Clock-in](https://github.com/UPB-FILS-MA/project-alexandra214)
I fixed it.

2024-05-19 09:55 UTC, alexandruradovici approved these changes

2024-05-19 12:32 UTC, ZamfirAndreiPaul approved these changes

2024-05-19 12:40 UTC, merged