Project documentation
UPB-FILS-MA/upb-fils-ma.github.io pull request #315
Opened 2024-05-18 12:45 UTC by illusion2626

### Pull Request Overview

This pull request adds/changes/fixes...

### Testing Strategy

This pull request was tested by...

### TODO or Help Wanted

This pull request still needs...

### Build

- [ ] Ran `npm build`.

### Author

Signed-off-by: Your Name <Your Email@example.com>

2024-05-18 12:49 UTC, alexandruradovici commented
Write the description.

2024-05-20 06:56 UTC, alexandruradovici requested changes
Please move the kicad files to your project's repository.

2024-05-20 12:48 UTC, illusion2626 commented
> Please move the kicad files to your project's repository.

I moved them to my project's repository.

2024-05-20 14:23 UTC, alexandruradovici commented on docs/project/2024/ionut.boghici/project.kicad_sch
Please move the cicada files to the project's repository.

2024-05-20 16:47 UTC, illusion2626 commented on docs/project/2024/ionut.boghici/project.kicad_sch
I'm sorry, can you please clarify?

2024-05-20 18:42 UTC, alexandruradovici commented on docs/project/2024/ionut.boghici/project.kicad_sch
Please move the kicad files to your project's repository. Fillow the discussion on Teans.

2024-05-20 19:19 UTC, alexandruradovici commented
> > Please move the kicad files to your project's repository.
> 
> 
> 
> I moved them to my project's repository. They're in a zip file, let me know if I should add them separately.

Please do not upload zip files in repositories, make a folder with them.

2024-05-20 19:21 UTC, alexandruradovici requested changes

2024-05-20 19:21 UTC, alexandruradovici commented on docs/project/2024/ionut.boghici/Kicad Schematic.PNG
Please do not use spaces in filenames.

2024-05-20 19:21 UTC, alexandruradovici commented on docs/project/2024/ionut.boghici/project.kicad_sch
This is a kicad file, please move it.

2024-05-20 19:21 UTC, alexandruradovici commented on docs/project/2024/ionut.boghici/~project.kicad_sch.lck
This is a kicad file, please move it.

2024-05-20 19:51 UTC, illusion2626 commented on docs/project/2024/ionut.boghici/Kicad Schematic.PNG
Changed it to have an underscore instead

2024-05-20 20:38 UTC, alexandruradovici approved these changes

2024-05-20 21:02 UTC, DTeodor-Alexaandru approved these changes

2024-05-20 21:08 UTC, merged