Lorena nistorescu hardware milestone
UPB-FILS-MA/upb-fils-ma.github.io pull request #348
Opened 2024-05-19 11:23 UTC by LorenaNistorescu

### Pull Request Overview

This pull request adds/changes/fixes...

### Testing Strategy

This pull request was tested by...

### TODO or Help Wanted

This pull request still needs...

### Build

- [ ] Ran `npm build`.

### Author

Signed-off-by: Your Name <Your Email@example.com>

2024-05-19 11:34 UTC, alexandruradovici requested changes

2024-05-19 11:34 UTC, alexandruradovici commented on docs/project/2024/Lorena Nistorescu/Project documentation(Nistorescu)
Please tename your folder correctly and the file correctly.

2024-05-19 12:06 UTC, alexandruradovici requested changes
Please read carefully the instructions on the Teams channel about submitting the project documentation and the project hardware milestone.

2024-05-20 19:16 UTC, DTeodor-Alexaandru approved these changes

2024-05-20 19:22 UTC, merged