Lorena Nistorescu-project documentation
UPB-FILS-MA/upb-fils-ma.github.io pull request #353
Opened 2024-05-19 12:48 UTC by LorenaNistorescu

### Pull Request Overview

This pull request adds/changes/fixes...

### Testing Strategy

This pull request was tested by...

### TODO or Help Wanted

This pull request still needs...

### Build

- [ ] Ran `npm build`.

### Author

Signed-off-by: Your Name <Your Email@example.com>

2024-05-19 19:13 UTC, alexandruradovici commented
@LorenaNistorescu please fix this so we can merge it. Rename the folder to your username and the documentation to *index.md*.

2024-05-19 19:14 UTC, alexandruradovici commented
Move the cicada files to your project's repository.

2024-05-19 20:19 UTC, alexandruradovici requested changes
Pleaee rename your folder to the username from upb and fill the pull request template.

2024-05-19 20:19 UTC, alexandruradovici commented on docs/project/2024/Lorena Nistorescu/index.md
> +
```suggestion
:::info
```

2024-05-19 20:27 UTC, LorenaNistorescu commented
I am trying, but honestly I can't find to change the folder of my name from
Lorena Nistorescu to maria.nistorescu...

În dum., 19 mai 2024 la 23:20, Alexandru Radovici ***@***.***>
a scris:

> ***@***.**** requested changes on this pull request.
>
> Pleaee rename your folder to the username from upb and fill the pull
> request template.
> ------------------------------
>
> In docs/project/2024/Lorena Nistorescu/index.md
> <https://github.com/UPB-FILS-MA/upb-fils-ma.github.io/pull/353#discussion_r1606096440>
> :
>
> > @@ -0,0 +1,114 @@
> +# Smart Door Lock System
> +Smart door lock: Keyless security for your space.
> +
>
> ⬇️ Suggested change
>
> -
> +:::info
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/UPB-FILS-MA/upb-fils-ma.github.io/pull/353#pullrequestreview-2065137915>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BIMC47HVVGHW4JE7DYCAUB3ZDECQHAVCNFSM6AAAAABH6K7B6SVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDANRVGEZTOOJRGU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-05-19 20:34 UTC, LorenaNistorescu commented
[image: image.png]Am ambele branch-uri aici, numele la folder nu il pot
schimba, nu stiu de ce nu merge editat..?

În dum., 19 mai 2024 la 23:27, Evelin Smith ***@***.***> a
scris:

> I am trying, but honestly I can't find to change the folder of my name
> from Lorena Nistorescu to maria.nistorescu...
>
> În dum., 19 mai 2024 la 23:20, Alexandru Radovici <
> ***@***.***> a scris:
>
>> ***@***.**** requested changes on this pull request.
>>
>> Pleaee rename your folder to the username from upb and fill the pull
>> request template.
>> ------------------------------
>>
>> In docs/project/2024/Lorena Nistorescu/index.md
>> <https://github.com/UPB-FILS-MA/upb-fils-ma.github.io/pull/353#discussion_r1606096440>
>> :
>>
>> > @@ -0,0 +1,114 @@
>> +# Smart Door Lock System
>> +Smart door lock: Keyless security for your space.
>> +
>>
>> ⬇️ Suggested change
>>
>> -
>> +:::info
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/UPB-FILS-MA/upb-fils-ma.github.io/pull/353#pullrequestreview-2065137915>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/BIMC47HVVGHW4JE7DYCAUB3ZDECQHAVCNFSM6AAAAABH6K7B6SVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDANRVGEZTOOJRGU>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***>
>>
>

2024-05-19 20:36 UTC, alexandruradovici commented
Clone the repo, change them locally, commit the chanfes and push them.

2024-05-20 14:24 UTC, alexandruradovici requested changes

2024-05-20 14:24 UTC, alexandruradovici commented on docs/project/2024/Lorena Nistorescu/DIAGRAMdoor.png
The folder name is still wrong, please use your username.

2024-05-20 19:17 UTC, closed without merging