Kicad setup
UPB-FILS-MA/upb-fils-ma.github.io pull request #36
Opened 2024-02-27 13:30 UTC by DTeodor-Alexaandru

### Pull Request Overview

This pull request adds a tutorials sections and a Kicad setup tutorial.

### Testing Strategy

N/A

### TODO or Help Wanted

Content review

### Build

- [x] Ran `npm build`.

### Author

Signed-off-by: Teodor-Alexandru Dicu - teodor.dicu@wyliodrin.com

2024-02-27 17:01 UTC, irina-b-dev approved these changes
Looks good to me

2024-02-27 17:30 UTC, alexandruradovici requested changes

2024-02-27 17:30 UTC, alexandruradovici commented on docs/tutorials/kicad.md
> +sidebar_position: 1
```suggestion
sidebar_position: 1
description: How to setup KiCad with the Raspberry Pi Pico
```

2024-02-27 17:30 UTC, alexandruradovici commented on docs/tutorials/kicad.md
> +There is a project file with the extension `.kicad_pro`, a schematic file with the extension `.kicad_sch`, and a board file with the extension `.kicad_pcb`. These files all share a name with your pro
```suggestion
A project contains three types of files:
- a file with the extension `.kicad_pro`
- a schematic file with the extension `.kicad_sch`
- a board file with the extension `.kicad_pcb`. 
```
The project files all share the name of your project.

2024-02-27 17:30 UTC, alexandruradovici commented on docs/tutorials/kicad.md
> +Before creating a new project go through the next steps to make upcoming changes take effect.
What do you mean by this?

2024-02-27 17:30 UTC, alexandruradovici commented on docs/tutorials/kicad.md
> +Kicad comes with a standard library that has a wide variety of components. For most project you will only need to import just a bunch of specific integrated circuits or custom components. This semest
```suggestion
Kicad comes with a standard library that has a wide variety of components. For most project you will only need to import just a bunch of specific integrated circuits or custom components. We will work with a *Raspberry Pi Pico W*, a development board designed around RP2040 microcontroller(MCU). KiCad's standard library has the RP2040 designs, but for the lab work we need to import the development board design files.
```

2024-02-27 17:30 UTC, alexandruradovici commented on docs/tutorials/kicad.md
> +Kicad comes with a standard library that has a wide variety of components. For most project you will only need to import just a bunch of specific integrated circuits or custom components. This semest
*but for the lab work we need to import the development board design files*

Please explain why this is needed.

2024-02-27 17:30 UTC, alexandruradovici commented on docs/tutorials/kicad.md
> +We can get the design files from this git [repository](https://github.com/bdubs-astro/Raspberry_Pi_Pico_W_Kicad_Files.git).
Why design files do we need to get?

2024-02-27 17:30 UTC, alexandruradovici commented on docs/tutorials/kicad.md
> +Create a directory where you want to store your design files and clone the repository there.
The downloaded design files?

2024-02-27 17:30 UTC, alexandruradovici commented on docs/tutorials/kicad.md
> +#### Import the symbol
What is a symbol?

2024-02-27 17:30 UTC, alexandruradovici commented on docs/tutorials/kicad.md
> +### Getting the design files
What are design files?

2024-02-27 17:30 UTC, alexandruradovici commented on docs/tutorials/kicad.md
> +Give your symbol an suitable nickname. This nickname will be the keyword you search for when you want to use the component.
What is the difference between a symbol and a component?

2024-02-27 17:30 UTC, alexandruradovici commented on docs/tutorials/kicad.md
> +You can move your `.kicad_sym` file to the symbol directory and use the relative path as shown for the rest of the components.
What is the symbol directory?

2024-02-27 17:30 UTC, alexandruradovici commented on docs/tutorials/kicad.md
> +#### Import the footprint
What is the footprint?

2024-02-27 17:30 UTC, alexandruradovici commented on docs/tutorials/kicad.md
> +These changes will take effect for the **new** projects created. For the old ones you have to do the link manually.
How would I do the link manually?

2024-02-27 17:30 UTC, alexandruradovici commented on docs/tutorials/_category_.json
> +
add newline

2024-02-29 08:07 UTC, alexandruradovici requested changes

2024-02-29 08:07 UTC, alexandruradovici commented on docs/tutorials/kicad.md
> +## What is a symbol?
```suggestion
### What is a symbol?
```

2024-02-29 08:07 UTC, alexandruradovici commented on docs/tutorials/kicad.md
> +## What is a footprint?
```suggestion
### What is a footprint?
```

2024-02-29 08:07 UTC, alexandruradovici commented on docs/tutorials/kicad.md
> +## What is a 3D model?
```suggestion
### What is a 3D model?
```

2024-02-29 08:07 UTC, alexandruradovici commented on docs/tutorials/kicad.md
> +![Symbol Libraries Import](images/symbol_libraries_import.png)
I suggest highlighting the imported line, otherwise it is hard to see the difference from the previous image.

2024-02-29 08:07 UTC, alexandruradovici commented on docs/tutorials/kicad.md
> +![Footprint Libraries Import](images/footprint_libraries.png)
Same here

2024-02-29 08:07 UTC, alexandruradovici commented on docs/tutorials/kicad.md
> +### Manual link
```suggestion
#### Manual link
```

2024-02-29 09:30 UTC, alexandruradovici approved these changes

2024-02-29 09:31 UTC, ZamfirAndreiPaul approved these changes

2024-02-29 09:34 UTC, merged