Project documentation
UPB-FILS-MA/upb-fils-ma.github.io pull request #361
Opened 2024-05-19 15:09 UTC by esxm

### Pull Request Overview

This pull request adds kicad schematic amd images of the hardware parts of the project and updates the log section

### Testing Strategy

This pull request was tested by Alkhalidy Essam

### TODO or Help Wanted

This pull request still needs to be checked that i have put everything for the hardware milestone

### Build

- [ ] Ran `npm build`.

### Author

Signed-off-by: Alkhalidy Essam <essam.al@stud.fils.upb.ro>

2024-05-19 15:45 UTC, alexandruradovici requested changes
Please rename the images.

2024-05-19 21:38 UTC, esxm commented
> Please rename the images.

i renamed the photos and put every file for the kicad not just the .sch one (in my project repositories)

2024-05-19 21:43 UTC, alexandruradovici approved these changes

2024-05-20 06:46 UTC, irina-b-dev approved these changes

2024-05-20 06:52 UTC, merged