Project documentation
UPB-FILS-MA/upb-fils-ma.github.io pull request #366
Opened 2024-05-19 16:08 UTC by anabat27

### Pull Request Overview

This pull request adds/changes/fixes KiCad schematics and project pictures.

### Testing Strategy

This pull request was tested by Ana-Maria Batagoi

### TODO or Help Wanted

This pull request still needs...

### Build

- [ ] Ran `npm build`.

### Author

Signed-off-by: Your Name <ana_maria.batagoi@stud.upb.fils.ro>

2024-05-19 17:48 UTC, alexandruradovici commented
Please fix the conflicts and add your name to the pull request description.

2024-05-19 18:10 UTC, alexandruradovici requested changes

2024-05-19 18:10 UTC, alexandruradovici commented on docs/project/2024/ana_maria.batagoi/kicad_ss.png
Please export the schematics instead of a screenshot.

2024-05-19 18:10 UTC, alexandruradovici commented on docs/project/2024/ana_maria.batagoi/image_2024-05-19_185658521.png
Please export the schematics instead of a screenshot.

2024-05-20 18:43 UTC, alexandruradovici approved these changes

2024-05-20 19:16 UTC, DTeodor-Alexaandru approved these changes

2024-05-20 19:30 UTC, merged