HardwareMilestone
UPB-FILS-MA/upb-fils-ma.github.io pull request #389
Opened 2024-05-19 19:32 UTC by AndreiAndreescu

### Author

Signed-off-by: Andreescu Andrei-Vlad <andrei.andreescu@stud.fils.upb.ro>

2024-05-19 19:42 UTC, alexandruradovici requested changes

2024-05-19 19:42 UTC, alexandruradovici commented on docs/project/2024/andrei.andreescu/index.md.md
> +2. [link](https://example3.com)
Please fix these links.

2024-05-19 19:42 UTC, alexandruradovici commented on docs/project/2024/andrei.andreescu/index.md.md
> +| [embedded-graphics](https://github.com/embedded-graphics/embedded-graphics) | 2D graphics library | Used for drawing to the display |
Do you need these libraries?

2024-05-19 19:51 UTC, kaanmeister commented
You have your schematic picture called `arhitecture.png` on your project documents but you wrote `architecture.png` on your index.md file to be able to upload picture. Change the picture name on your index.md file to be able to solve the build error.

2024-05-19 19:54 UTC, kaanmeister commented
> You have your schematic picture called `arhitecture.png` on your project documents but you wrote `architecture.png` on your index.md file to be able to upload picture. Change the picture name on your index.md file to be able to solve the build error.

![issuepullreq](https://github.com/UPB-FILS-MA/upb-fils-ma.github.io/assets/153783603/ea33f0cf-44e5-4bcc-93f8-04e55472ff8f)

For better understanding.

2024-05-19 20:01 UTC, alexandruradovici approved these changes

2024-05-19 20:17 UTC, alexandruradovici requested changes

2024-05-19 20:17 UTC, alexandruradovici commented on docs/project/2024/andrei.andreescu/kicad.jpg
Export the schematics instead of the screenshot.

2024-05-19 20:39 UTC, alexandruradovici approved these changes

2024-05-19 20:49 UTC, alexandruradovici approved these changes

2024-05-20 06:46 UTC, irina-b-dev approved these changes

2024-05-20 06:52 UTC, merged