hardware milestone added
UPB-FILS-MA/upb-fils-ma.github.io pull request #390
Opened 2024-05-19 19:39 UTC by MadalinaEliana

### Pull Request Overview

This pull request adds hardware milestone for the project

### Build

- [ ] Ran `npm build`.

### Author

Signed-off-by: Stefan Madalina-Eliana <madalina.stefan2013@gmail.com>

2024-05-19 19:40 UTC, alexandruradovici requested changes
Pleaee move the kicad files to your project's repository.

2024-05-19 20:17 UTC, alexandruradovici requested changes

2024-05-19 20:17 UTC, alexandruradovici commented on docs/project/2024/madalina.stefan2007/images/WhatsApp Image 2024-05-19 .jpg
Rename these files

2024-05-19 20:22 UTC, alexandruradovici approved these changes

2024-05-19 20:22 UTC, alexandruradovici commented on docs/project/2024/madalina.stefan2007/images/hardware1.jpg
Have you used these files in the documentation?

2024-05-19 20:24 UTC, MadalinaEliana commented on docs/project/2024/madalina.stefan2007/images/hardware1.jpg
i haven't. i thought they were supposed to be just for you to see our projects. i'll add them now.

2024-05-19 20:34 UTC, alexandruradovici submitted a review, later dismissed

2024-05-19 20:49 UTC, alexandruradovici approved these changes

2024-05-19 21:00 UTC, alexandruradovici approved these changes

2024-05-20 06:45 UTC, irina-b-dev approved these changes

2024-05-20 06:56 UTC, ZamfirAndreiPaul approved these changes

2024-05-20 07:00 UTC, merged