Added documentation and hardware milestone and uploaded pictures of the project.
UPB-FILS-MA/upb-fils-ma.github.io pull request #417
Opened 2024-05-21 13:33 UTC by FilipDenisa

### Pull Request Overview

This pull request adds/changes/fixes...

### Testing Strategy

This pull request was tested by Filip Denisa Mihaela

### TODO or Help Wanted

This pull request still needs...

### Build

- [ ] Ran `npm build`.

### Author

Signed-off-by: Filip Denisa Mihaela <mihaelaa0636@gmail.com>

2024-05-21 13:34 UTC, FilipDenisa commented
Sorry for the late submit, I had some problems with my github as soon as I solved it, I just submitted a pull request, sorry for incovience! @alexandruradovici

2024-05-24 15:54 UTC, alexandruradovici requested changes

2024-05-24 15:54 UTC, alexandruradovici commented on docs/project/2024/filip.denisa/hardware (1).jpeg
Please delete the spaces from the filename.

2024-05-25 13:12 UTC, FilipDenisa commented on docs/project/2024/filip.denisa/hardware (1).jpeg
I changed the filenames, it is ready for review! sorry for the inconvenience @alexandruradovici!

2024-05-26 23:33 UTC, FilipDenisa commented
I added the Software milestone to this pull request! @alexandruradovici

2024-06-09 18:44 UTC, alexandruradovici requested changes
Please delete the project source files, they should be placed in the project's repository.

2025-02-06 12:33 UTC, closed without merging