Update index.md
UPB-FILS-MA/upb-fils-ma.github.io pull request #419
Opened 2024-05-23 11:44 UTC by ALINA308

### Pull Request Overview

This pull request adds the title of the project

### Author

Signed-off-by: Bilciurescu Elena-Alina <alina2018a1b1@gmail.com>
                        Toma Daria-Maria <dariatoma1810@gmail.com>

2024-05-27 05:56 UTC, irina-b-dev submitted a review, later dismissed

2024-06-09 08:05 UTC, alexandruradovici requested changes

2024-06-09 08:05 UTC, alexandruradovici commented on docs/project/2024/elena.bilciurescu_daria_maria.toma/index.md
> +Rusty the Robot
```suggestion
# Rusty the Robot
```

2024-06-09 16:29 UTC, alexandruradovici approved these changes

2024-06-09 18:46 UTC, TeodoraMiu approved these changes

2024-06-09 18:56 UTC, merged