Project documentation
UPB-FILS-MA/upb-fils-ma.github.io pull request #451
Opened 2024-05-26 20:49 UTC by sadtoni

### Pull Request Overview

This pull request adds the code for the project

### Testing Strategy

This pull request was tested by antonio georgescu

### TODO or Help Wanted

This pull request still needs to implement the connexion between the remote and the car

### Build

- [ ] Ran `npm build`.

### Author

Signed-off-by: antonio georgescu <mihai.georgescu2508@stud.fils.upb.ro>

2024-05-26 20:50 UTC, sadtoni commented
@alexandruradovici am incarcat acum codul, e ok?

2024-06-09 09:21 UTC, alexandruradovici requested changes
Please delete the source code from this repository, the source code has to be in your project's repository.

2024-06-09 11:21 UTC, sadtoni commented
@alexandruradovici am sters codul din repo asta, e ok acum?

2024-06-09 11:22 UTC, alexandruradovici approved these changes

2024-06-09 18:44 UTC, TeodoraMiu approved these changes

2024-06-09 18:50 UTC, merged