Lab 03 - Interrupts and timers
UPB-FILS-MA/upb-fils-ma.github.io pull request #63
Opened 2024-03-18 20:56 UTC by irina-b-dev

### Pull Request Overview

This pull request adds  lab03 - Interrupts and timers

### TODO or Help Wanted

This pull request needs  review

### Build

- [ x] Ran `npm build`.

### Author

Signed-off-by: Irina Bradu - [irina.bradu@wyliodrin.com](mailto:irina.bradu@wyliodrin.com)

2024-03-19 18:04 UTC, alexandruradovici requested changes

2024-03-19 18:04 UTC, alexandruradovici commented on docs/lab/03/03.md
> +
Register the function first, after show the examples of enabling SysTick.

2024-03-19 18:04 UTC, alexandruradovici commented on docs/lab/03/03.md
> +## Inspect binaries
I would add this section after explaining the interrupt vector.

2024-03-19 18:04 UTC, alexandruradovici commented on docs/lab/03/03.md
> +If this happens please use llvm-objdump script directly like so
```suggestion
`cargo objdump` and `rust-objdump` tools use llvm's `objdump` tool.
Some terminals do not parse parameters proxied to `llvm-objdump` command.
If this happens please use `llvm-objdump` script directly like so
```

2024-03-19 18:04 UTC, alexandruradovici commented on docs/lab/03/03.md
> +## What is an exception ?
```suggestion
## What is an exception? 
```

2024-03-19 18:04 UTC, alexandruradovici commented on docs/lab/03/03.md
> +## What is an interrupt ?
```suggestion
## What is an interrupt?
```

2024-03-19 18:04 UTC, alexandruradovici commented on docs/lab/03/03.md
> +#### Supported interrupt request signals (IRQ)
```suggestion
#### Available interrupt request signals (IRQ)
```

2024-03-19 18:04 UTC, alexandruradovici commented on docs/lab/03/03.md
> +- First, the dynamic priority level configured per interrupt by the NVIC_IPR0-7 registers. The Cortex-M0+ implements
```suggestion
- First, the dynamic priority level configured per interrupt by the `NVIC_IPR0-7` registers. The Cortex-M0+ implements
```

2024-03-19 18:04 UTC, alexandruradovici commented on docs/lab/03/03.md
> +An interrupt handler is a function that should be executed when a the interrupt signal is triggered. This function must have the signature **fn()** without any arguments or return value.
```suggestion
An interrupt handler is a function that should be executed when a the interrupt signal is triggered. This function must have the signature `fn()` without any arguments or return value.
```

2024-03-19 22:25 UTC, irina-b-dev commented on docs/lab/03/03.md
> +ARM Cortex-M microcontrollers use a similar concept to the IVT called Nested Vectored Interrupt Controller (NVIC).The NVIC is specifically designed to handle these interrupts more efficiently. Interr
removed comparison

2024-03-20 00:58 UTC, alexandruradovici approved these changes
The code for `embedded-hal` still needs some modifications, we'll have another pull request,

2024-03-20 09:27 UTC, irina-nita approved these changes

2024-03-20 09:33 UTC, merged